# Generated by Django 4.0.2 on 2022-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('imdbID', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=200)),
                ('transactionId', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
            ],
        ),
    ]
