# Generated by Django 3.2 on 2022-03-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='static/movie'),
        ),
    ]
