# Generated by Django 3.2 on 2022-04-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='DVD',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Metascore',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbVotes',
        ),
    ]
